version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo "ci start"

  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          name: check-auto-deploy
          command: |
            COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%s)
            TRIGGER_MATCH_PATTERN="^Update dependency capifla to.*$"
            echo COMMIT_MESSAGE
            if [[ ${COMMIT_MESSAGE} =~ ${TRIGGER_MATCH_PATTERN} ]]; then
              echo "execute auto deploy"
            else
              echo "stop auto deploy"
              circleci-agent step halt
            fi
      - run:
          name: create-ami-and-scaling
          command: |
            echo 'start AWS CLI test'
            aws --version
            aws s3 ls


workflows:
  jobs:
    - build
    - aws-cli-example:
        requires:
          - build
      filters:
        branches:
          only: master
