version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            git log -1 --oneline

  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          name: deploy
          command: |
            echo 'start AWS CLI test'
            aws --version
            aws s3 ls


workflows:
  build:
    jobs:
      - build
      - aws-cli-example
      filters:
        branches:
          only:
            - master
